[masters]
3.218.249.237 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-key.pem

[workers]
100.25.77.60 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-key.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3