[masters]
3.237.232.41 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-key.pem

[workers]
3.234.143.171 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-key.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3